name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - name: Upload TabsBuilder.dll
        uses: actions/upload-artifact@v4
        with:
          name: TabsBuilder.dll
          path: |
            **/Release/net6.0/TabsBuilder.dll

      - name: Upload Cosmella.TabApi nupkg
        uses: actions/upload-artifact@v4
        with:
          name: Cosmella.TabApi.nupkg
          path: |
            **/*.nupkg

      - name: Prepare artifact folder
        run: |
          mkdir -p artifact
          find . -type f -name "*.dll" -path "*/Release/*" -exec cp {} artifact/ \;
          
          cp manifest.json README.md icon.png artifact/
          if [ -f CHANGELOG.md ]; then
            cp CHANGELOG.md artifact/
          fi

      - name: Upload artifact folder
        uses: actions/upload-artifact@v4
        with:
          name: Thunderstore
          path: artifact/
